// Generated by tools/tokens from the DESIGN.md frontmatter in:
// _bmad-output/planning-artifacts/ux-designs/ux-pay-per-snooze-2026-09-26/DESIGN.md
// Do not edit by hand: run ./gradlew generateTokens. ./gradlew checkTokens (qualityGate) fails on any drift.
@file:Suppress("MagicNumber")

package com.yawnandpawn.app.ui.theme

import androidx.compose.foundation.shape.CornerSize
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** One style of the DESIGN.md type ramp. */
data class PpsTypeToken(
    val fontSize: TextUnit,
    val lineHeight: TextUnit,
    val fontWeight: FontWeight,
)

/** Design tokens from DESIGN.md. Use them through `PpsTheme`, not directly in screens. */
object PpsTokens {
    /** Light colour set. */
    object Light {
        val bg = Color(0xFFFAF8F5)
        val surface = Color(0xFFFFFFFF)
        val surfaceVariant = Color(0xFFF1EEE9)
        val outline = Color(0xFF8A837A)
        val outlineSubtle = Color(0xFFE4DED6)
        val text = Color(0xFF1A1714)
        val textSecondary = Color(0xFF5E5850)
        val accent = Color(0xFFD96F14)
        val onAccent = Color(0xFF1A1004)
        val accentText = Color(0xFFA8520A)
        val success = Color(0xFF0F5534)
        val snoozed = Color(0xFFB4472F)
        val missed = Color(0xFF6E675F)
        val error = Color(0xFFB3261E)
        val disabledContainer = Color(0xFFEAE5DE)
        val disabledContent = Color(0xFF5F5951)
        val inverseSurface = Color(0xFF1A1714)
        val inverseText = Color(0xFFFAF8F5)
        val inverseAccent = Color(0xFFF5A04E)
    }

    /** Dark colour set. */
    object Dark {
        val bg = Color(0xFF111214)
        val surface = Color(0xFF1A1B1E)
        val surfaceVariant = Color(0xFF24262A)
        val outline = Color(0xFF6B6D73)
        val outlineSubtle = Color(0xFF2E3035)
        val text = Color(0xFFF2EFEA)
        val textSecondary = Color(0xFFA9A39A)
        val accent = Color(0xFFF5A04E)
        val onAccent = Color(0xFF1A1004)
        val accentText = Color(0xFFF5A04E)
        val success = Color(0xFF8BE0B2)
        val snoozed = Color(0xFFE58A72)
        val missed = Color(0xFF8E8880)
        val error = Color(0xFFF2B8B5)
        val disabledContainer = Color(0xFF27292D)
        val disabledContent = Color(0xFFA39D94)
        val inverseSurface = Color(0xFFF2EFEA)
        val inverseText = Color(0xFF111214)
        val inverseAccent = Color(0xFFA8520A)
    }

    /** Sunrise colour set. */
    object Sunrise {
        val bg = Color(0xFFFFF6EA)
        val surface = Color(0xFFFFFFFF)
        val surfaceVariant = Color(0xFFF8ECDD)
        val outline = Color(0xFF8A837A)
        val outlineSubtle = Color(0xFFEBDDCB)
        val text = Color(0xFF1A1714)
        val textSecondary = Color(0xFF5E5850)
        val accent = Color(0xFFD96F14)
        val onAccent = Color(0xFF1A1004)
        val accentText = Color(0xFFA8520A)
        val success = Color(0xFF0F5534)
        val error = Color(0xFFB3261E)
        val disabledContainer = Color(0xFFF2E6D7)
        val disabledContent = Color(0xFF5F5951)
        val inverseSurface = Color(0xFF1A1714)
        val inverseText = Color(0xFFFFF6EA)
        val sunriseGradientTop = Color(0xFFFFE3C2)
    }

    /** Every colour token by its DESIGN.md key. */
    val colorsByName: Map<String, Color> =
        mapOf(
            "bg" to Light.bg,
            "surface" to Light.surface,
            "surface-variant" to Light.surfaceVariant,
            "outline" to Light.outline,
            "outline-subtle" to Light.outlineSubtle,
            "text" to Light.text,
            "text-secondary" to Light.textSecondary,
            "accent" to Light.accent,
            "on-accent" to Light.onAccent,
            "accent-text" to Light.accentText,
            "success" to Light.success,
            "snoozed" to Light.snoozed,
            "missed" to Light.missed,
            "error" to Light.error,
            "disabled-container" to Light.disabledContainer,
            "disabled-content" to Light.disabledContent,
            "inverse-surface" to Light.inverseSurface,
            "inverse-text" to Light.inverseText,
            "inverse-accent" to Light.inverseAccent,
            "bg-dark" to Dark.bg,
            "surface-dark" to Dark.surface,
            "surface-variant-dark" to Dark.surfaceVariant,
            "outline-dark" to Dark.outline,
            "outline-subtle-dark" to Dark.outlineSubtle,
            "text-dark" to Dark.text,
            "text-secondary-dark" to Dark.textSecondary,
            "accent-dark" to Dark.accent,
            "on-accent-dark" to Dark.onAccent,
            "accent-text-dark" to Dark.accentText,
            "success-dark" to Dark.success,
            "snoozed-dark" to Dark.snoozed,
            "missed-dark" to Dark.missed,
            "error-dark" to Dark.error,
            "disabled-container-dark" to Dark.disabledContainer,
            "disabled-content-dark" to Dark.disabledContent,
            "inverse-surface-dark" to Dark.inverseSurface,
            "inverse-text-dark" to Dark.inverseText,
            "inverse-accent-dark" to Dark.inverseAccent,
            "bg-sunrise" to Sunrise.bg,
            "surface-sunrise" to Sunrise.surface,
            "surface-variant-sunrise" to Sunrise.surfaceVariant,
            "outline-sunrise" to Sunrise.outline,
            "outline-subtle-sunrise" to Sunrise.outlineSubtle,
            "text-sunrise" to Sunrise.text,
            "text-secondary-sunrise" to Sunrise.textSecondary,
            "accent-sunrise" to Sunrise.accent,
            "on-accent-sunrise" to Sunrise.onAccent,
            "accent-text-sunrise" to Sunrise.accentText,
            "success-sunrise" to Sunrise.success,
            "error-sunrise" to Sunrise.error,
            "disabled-container-sunrise" to Sunrise.disabledContainer,
            "disabled-content-sunrise" to Sunrise.disabledContent,
            "inverse-surface-sunrise" to Sunrise.inverseSurface,
            "inverse-text-sunrise" to Sunrise.inverseText,
            "sunrise-gradient-top" to Sunrise.sunriseGradientTop,
        )

    /** Type ramp (DESIGN.md `typography`). */
    object Type {
        val clockXl =
            PpsTypeToken(
                fontSize = 88.sp,
                lineHeight = 92.sp,
                fontWeight = FontWeight(300),
            )
        val display =
            PpsTypeToken(
                fontSize = 48.sp,
                lineHeight = 52.sp,
                fontWeight = FontWeight(500),
            )
        val headline =
            PpsTypeToken(
                fontSize = 28.sp,
                lineHeight = 34.sp,
                fontWeight = FontWeight(600),
            )
        val title =
            PpsTypeToken(
                fontSize = 20.sp,
                lineHeight = 26.sp,
                fontWeight = FontWeight(600),
            )
        val buttonWake =
            PpsTypeToken(
                fontSize = 20.sp,
                lineHeight = 24.sp,
                fontWeight = FontWeight(500),
            )
        val body =
            PpsTypeToken(
                fontSize = 16.sp,
                lineHeight = 24.sp,
                fontWeight = FontWeight(400),
            )
        val label =
            PpsTypeToken(
                fontSize = 14.sp,
                lineHeight = 20.sp,
                fontWeight = FontWeight(500),
            )
        val caption =
            PpsTypeToken(
                fontSize = 12.sp,
                lineHeight = 16.sp,
                fontWeight = FontWeight(400),
            )
    }

    /** Corner radii (DESIGN.md `rounded`). `9999px` means fully rounded (50%). */
    object Rounded {
        val sm = CornerSize(8.dp)
        val md = CornerSize(16.dp)
        val lg = CornerSize(28.dp)
        val full = CornerSize(percent = 50)
    }

    /** Spacing and target sizes (DESIGN.md `spacing`, dp values only). */
    object Spacing {
        val space1: Dp = 4.dp
        val space2: Dp = 8.dp
        val space3: Dp = 12.dp
        val space4: Dp = 16.dp
        val space5: Dp = 20.dp
        val space6: Dp = 24.dp
        val space8: Dp = 32.dp
        val screenMargin: Dp = 20.dp
        val sectionGap: Dp = 24.dp
        val cardPadding: Dp = 16.dp
        val targetMin: Dp = 48.dp
        val targetWake: Dp = 64.dp
        val targetWakeHero: Dp = 72.dp
        val ringStroke: Dp = 8.dp
    }
}
