package com.yawnandpawn.app.tokens

/** The three colour sets of DESIGN.md: Light (no suffix), Dark (`-dark`), Sunrise (`-sunrise`, `sunrise-*`). */
enum class ColorSet(
    val objectName: String,
) {
    Light("Light"),
    Dark("Dark"),
    Sunrise("Sunrise"),
    ;

    companion object {
        fun of(tokenName: String): ColorSet =
            when {
                tokenName.endsWith("-dark") -> Dark
                tokenName.endsWith("-sunrise") || tokenName.startsWith("sunrise-") -> Sunrise
                else -> Light
            }

        /** Kotlin property name inside the set object: suffix dropped, kebab-case to camelCase. */
        fun propertyName(tokenName: String): String = camelCase(tokenName.removeSuffix("-dark").removeSuffix("-sunrise"))
    }
}

/** kebab-case to camelCase: `surface-variant` -> `surfaceVariant`, `clock-xl` -> `clockXl`. */
fun camelCase(name: String): String {
    val parts = name.split('-').filter { it.isNotEmpty() }
    return parts.first() + parts.drop(1).joinToString("") { part -> part.replaceFirstChar { it.uppercaseChar() } }
}

/** Spacing keys may be numbers (`'1'`); those become `space1`. */
fun spacingPropertyName(name: String): String = if (name.first().isDigit()) "space$name" else camelCase(name)

/**
 * Renders [DesignTokens] as the Kotlin source of `PpsTokens.kt`. Deterministic: the same tokens
 * always give byte-identical output (LF line endings), so `checkTokens` can diff it. The output
 * is formatted to pass Spotless/ktlint as committed.
 */
object TokenSourceWriter {
    private val identifier = Regex("^[a-z][A-Za-z0-9]*$")

    fun render(
        tokens: DesignTokens,
        packageName: String,
        sourcePath: String,
    ): String {
        checkNames(tokens)
        val out = StringBuilder()
        appendHeader(out, packageName, sourcePath)
        out.appendLine("/** Design tokens from DESIGN.md. Use them through `PpsTheme`, not directly in screens. */")
        out.appendLine("object PpsTokens {")
        appendColors(out, tokens.colors)
        appendType(out, tokens.typography)
        appendShapesAndSpacing(out, tokens)
        out.appendLine("}")
        return out.toString()
    }

    private fun appendHeader(
        out: StringBuilder,
        packageName: String,
        sourcePath: String,
    ) {
        out.appendLine("// Generated by tools/tokens from the DESIGN.md frontmatter in:")
        out.appendLine("// $sourcePath")
        out.appendLine("// Do not edit by hand: run ./gradlew generateTokens. ./gradlew checkTokens (qualityGate) fails on any drift.")
        out.appendLine("@file:Suppress(\"MagicNumber\")")
        out.appendLine()
        out.appendLine("package $packageName")
        out.appendLine()
        listOf(
            "androidx.compose.foundation.shape.CornerSize",
            "androidx.compose.ui.graphics.Color",
            "androidx.compose.ui.text.font.FontWeight",
            "androidx.compose.ui.unit.Dp",
            "androidx.compose.ui.unit.TextUnit",
            "androidx.compose.ui.unit.dp",
            "androidx.compose.ui.unit.sp",
        ).forEach { out.appendLine("import $it") }
        out.appendLine()
        out.appendLine("/** One style of the DESIGN.md type ramp. */")
        out.appendLine("data class PpsTypeToken(")
        out.appendLine("    val fontSize: TextUnit,")
        out.appendLine("    val lineHeight: TextUnit,")
        out.appendLine("    val fontWeight: FontWeight,")
        out.appendLine(")")
        out.appendLine()
    }

    private fun appendColors(
        out: StringBuilder,
        colors: List<ColorToken>,
    ) {
        val bySet = colors.groupBy { ColorSet.of(it.name) }
        ColorSet.entries.forEach { set ->
            out.appendLine("    /** ${set.objectName} colour set. */")
            out.appendLine("    object ${set.objectName} {")
            bySet[set].orEmpty().forEach { color ->
                out.appendLine("        val ${ColorSet.propertyName(color.name)} = Color(0x${argb(color.hex)})")
            }
            out.appendLine("    }")
            out.appendLine()
        }
        out.appendLine("    /** Every colour token by its DESIGN.md key. */")
        out.appendLine("    val colorsByName: Map<String, Color> =")
        out.appendLine("        mapOf(")
        colors.forEach { color ->
            val set = ColorSet.of(color.name)
            out.appendLine("            \"${color.name}\" to ${set.objectName}.${ColorSet.propertyName(color.name)},")
        }
        out.appendLine("        )")
        out.appendLine()
    }

    private fun appendType(
        out: StringBuilder,
        typography: List<TypeToken>,
    ) {
        out.appendLine("    /** Type ramp (DESIGN.md `typography`). */")
        out.appendLine("    object Type {")
        typography.forEach { type ->
            out.appendLine("        val ${camelCase(type.name)} =")
            out.appendLine("            PpsTypeToken(")
            out.appendLine("                fontSize = ${type.fontSizeSp}.sp,")
            out.appendLine("                lineHeight = ${type.lineHeightSp}.sp,")
            out.appendLine("                fontWeight = FontWeight(${type.fontWeight}),")
            out.appendLine("            )")
        }
        out.appendLine("    }")
        out.appendLine()
    }

    private fun appendShapesAndSpacing(
        out: StringBuilder,
        tokens: DesignTokens,
    ) {
        out.appendLine("    /** Corner radii (DESIGN.md `rounded`). `9999px` means fully rounded (50%). */")
        out.appendLine("    object Rounded {")
        tokens.rounded.forEach { rounded ->
            val value =
                when (val radius = rounded.radius) {
                    is Radius.Dp -> "CornerSize(${radius.value}.dp)"
                    Radius.Full -> "CornerSize(percent = 50)"
                }
            out.appendLine("        val ${camelCase(rounded.name)} = $value")
        }
        out.appendLine("    }")
        out.appendLine()
        out.appendLine("    /** Spacing and target sizes (DESIGN.md `spacing`, dp values only). */")
        out.appendLine("    object Spacing {")
        tokens.spacing.forEach { spacing ->
            out.appendLine("        val ${spacingPropertyName(spacing.name)}: Dp = ${spacing.dp}.dp")
        }
        out.appendLine("    }")
    }

    /** `#RRGGBB` to `FFRRGGBB`, `#RRGGBBAA` to `AARRGGBB` (the Compose `Color(0xAARRGGBB)` order). */
    private fun argb(hex: String): String {
        val digits = hex.removePrefix("#")
        return if (digits.length == RGBA_DIGITS) digits.substring(RGB_DIGITS) + digits.substring(0, RGB_DIGITS) else "FF$digits"
    }

    private const val RGB_DIGITS = 6
    private const val RGBA_DIGITS = 8

    private fun checkNames(tokens: DesignTokens) {
        val groups =
            ColorSet.entries.map { set ->
                val colors = tokens.colors.filter { ColorSet.of(it.name) == set }
                "colors (${set.objectName})" to colors.map { it.name to ColorSet.propertyName(it.name) }
            } +
                listOf(
                    "typography" to tokens.typography.map { it.name to camelCase(it.name) },
                    "rounded" to tokens.rounded.map { it.name to camelCase(it.name) },
                    "spacing" to tokens.spacing.map { it.name to spacingPropertyName(it.name) },
                )
        groups.forEach { (group, names) ->
            names.forEach { (key, property) ->
                if (!identifier.matches(property)) throw TokenParseException("Token '$group.$key' gives an invalid Kotlin name '$property'")
            }
            names.groupBy { it.second }.filterValues { it.size > 1 }.forEach { (property, keys) ->
                throw TokenParseException("Tokens ${keys.map { it.first }} in $group all map to the Kotlin name '$property'")
            }
        }
    }
}
